/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/womp.gltf')
  return (
    <group {...props} dispose={null} scale = {0.3}>
      <mesh geometry={nodes.Node.geometry} material={materials.material_0} />
    </group>
  )
}

useGLTF.preload('/womp.gltf')
